package com.machina.mdevtools.tasks.modreload;

import java.util.concurrent.CompletableFuture;

import javax.annotation.Nonnull;

import com.hypixel.hytale.server.core.asset.common.CommonAsset;

/**
 * POC: Dynamic Asset implementation that demonstrates sending assets
 * to players without registering them in AssetPacks.
 * 
 * This class creates a CommonAsset with dynamically generated bytes.
 */
public class ModAsset extends CommonAsset {
    private final byte[] assetBytes;
    
    /**
     * Creates a dynamic asset with the given name and bytes.
     * The hash will be calculated automatically from the bytes.
     * 
     * @param name The asset name/path (e.g., "msecuritytest/poc/dynamic-test.png")
     * @param bytes The asset bytes (e.g., PNG image data)
     */
    public ModAsset(@Nonnull String name, @Nonnull byte[] bytes) {
        super(name, bytes); // Hash is calculated automatically from bytes
        this.assetBytes = bytes;
    }
    
    /**
     * Creates a dynamic asset with the given name, hash, and bytes.
     * Use this constructor if you want to specify the hash manually.
     * 
     * @param name The asset name/path
     * @param hash The asset hash (64 character hex string)
     * @param bytes The asset bytes
     */
    public ModAsset(@Nonnull String name, @Nonnull String hash, @Nonnull byte[] bytes) {
        super(name, hash, bytes);
        this.assetBytes = bytes;
    }
    
    /**
     * Returns the asset bytes as a completed future.
     * This method is called when the asset blob is needed.
     */
    @Override
    @Nonnull
    protected CompletableFuture<byte[]> getBlob0() {
        return CompletableFuture.<byte[]>completedFuture(assetBytes);
    }
}
